name: run generate_killed_list python script on PR

on:
  pull_request:
    branches:
      - '*'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: run python script
        run: |
          python generate_killed_list.py
